### ISSUE TITLE
`read_int64_le()` cannot read a large integer

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/bson_c_lib#19]
### Bug Report
The implementation of `read_int64_le()` has an issue. It does not parse an integer larger than INT32_MAX correctly.

##### Reproduction Steps
1. Check out commit e825276e7694e66a627f356a541e7977885b24b6 which adds unit tests for the function.
2. Run the unit tests with:
```
$ autoreconf -i
$ ./configure
$ make check
```

Note that you will need to install libcheck (`sudo apt-get install check`) for it.

##### Expected Behavior
The unit tests pass.

##### Observed Behavior
The unit tests fail.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 LTS 64-bit

##### Test Case, Sample Code, and / or Example App
Output of the unit tests is attached.
[bson_util_test.log](https://github.com/smartdevicelink/bson_c_lib/files/2674861/bson_util_test.log)

**Comment by jacobkeeler** [comment]
Closing with the merge of #20
