### ISSUE TITLE
`bson_object_from_bytes()` may cause buffer over-run on corrupted input

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/bson_c_lib#21]
### Bug Report
The function `bson_object_from_bytes()` does not take into account the size of input data. If the input data is corrupted or malformed, the function may continue reading beyond the allocated buffer and may cause undefined behavior.

##### Reproduction Steps
1. Check out commit 3d45f7a28632fab7eee1c26bd3765c91ef94268a which adds unit tests with corrupted input.
2. Run the unit tests with:
```
$ autoreconf -i
$ ./configure
$ make check
```
3. Also, use `valgrind` to detect memory issues.
```
$ valgrind test/bson_object_test
```

Note that you will need to install libcheck (`sudo apt-get install check`) to build and run unit tests.

##### Expected Behavior
The unit tests pass, and no memory issue is observed.

##### Observed Behavior
Valgrind reports memory issues. The tests may fail.

##### OS & Version Information
* OS/Version: Ubuntu 16.04 LTS 64-bit

##### Test Case, Sample Code, and / or Example App
Output of valgrind is attached:
[buffer_overrun_valgrind.txt](https://github.com/smartdevicelink/bson_c_lib/files/2674914/buffer_overrun_valgrind.txt)

**Comment by jacobkeeler** [comment]
Closing with the merge of #22, #23, and #24
