### ISSUE TITLE
Exclude libunwind.a from being exported in the Android makefile

### ISSUE THREAD

**Issue by robertdtyler** [smartdevicelink/bson_c_lib#38]
Currently the when building bson_c_lib for Android, the resulting libbson-c-lib.so file includes exported global unwind functions which can cause crashes on 32-bit Android ARM phones if this library is included in another application also using native code elsewhere with exception handling.

Source:  https://android.googlesource.com/platform/ndk/+/master/docs/BuildSystemMaintainers.md#Unwinding

The Android.mk file needs to be updated to exclude libunwind.a when building so that these symbols aren't being exported.

**Comment by jacobkeeler** [comment]
@robertdtyler Please sign the [CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

**Comment by robertdtyler** [comment]
@jacobkeeler done.  Signed w/ my work email address (rtyler@cisco.com) as opposed to my email on this personal GH account, hopefully that's ok.  Let me know if there's anything else that I need to provide too; I didn't know about this otherwise I would have done it sooner thanks for the heads up!

**Comment by jacobkeeler** [comment]
Closing with the merge of #39. Will be released as part of version 1.2.2
