### ISSUE TITLE
Fix conversion warning messages

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/bson_c_lib#42]
# Bug Report
When the bson_c_lib is added to the sdl_ios library as a submodule, Xcode generates six warning messages when the sdl_ios library is compiled. The code should be updated so the following warnings no longer show up. 

### 1
https://github.com/smartdevicelink/bson_c_lib/blob/9cacdaffa64bba1231489e2a28d2045e0c6e93a4/src/bson_array.c#L55
`element->type` is underlined with the warning: **Implicit conversion loses integer precision: 'element_type' (aka 'enum element_type') to 'uint8_t' (aka 'unsigned char')**

### 2
https://github.com/smartdevicelink/bson_c_lib/blob/9cacdaffa64bba1231489e2a28d2045e0c6e93a4/src/bson_array.c#L147
In the `bson_array_from_bytes_len()` method, `size` is underlined with the warning: **Implicit conversion changes signedness: 'int32_t' (aka 'int') to 'size_t' (aka 'unsigned long')**

### 3
https://github.com/smartdevicelink/bson_c_lib/blob/9cacdaffa64bba1231489e2a28d2045e0c6e93a4/src/bson_array.c#L243
`bufferLength` is underlined with the warning: **Implicit conversion changes signedness: 'int32_t' (aka 'int') to 'unsigned long'**

### 1
https://github.com/smartdevicelink/bson_c_lib/blob/9cacdaffa64bba1231489e2a28d2045e0c6e93a4/src/bson_object.c#L75
`element->type` is underlined with the warning: **"Implicit conversion loses integer precision: 'element_type' (aka 'enum element_type') to 'uint8_t' (aka 'unsigned char')"**

### 2
https://github.com/smartdevicelink/bson_c_lib/blob/9cacdaffa64bba1231489e2a28d2045e0c6e93a4/src/bson_object.c#L168
In the `bson_object_from_bytes_len()` method, `size` is underlined with the warning: **Implicit conversion changes signedness: 'int32_t' (aka 'int') to 'size_t' (aka 'unsigned long')**

### 3
https://github.com/smartdevicelink/bson_c_lib/blob/9cacdaffa64bba1231489e2a28d2045e0c6e93a4/src/bson_object.c#L264
`bufferLength` is underlined with the warning: **Implicit conversion changes signedness: 'int32_t' (aka 'int') to 'unsigned long'**

**Comment by jacobkeeler** [comment]
Closing with the merge of #43
